<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>ed9a459c-22b2-4b51-8bff-ec6368c129ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='creditHtmlForm']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://leedonline-api-stg.usgbc.org/Credit/form/dkdnc2Z3Q1NqckdpWWg4OThxWmlHUDlWN1dsM1pDRnRsdXVacVI3UjZFeFhiSWw4ckpMUFYyZ0dpc1FpKzUySWs1OWpMeXdWdUoyRGVHdVREMWUyZ3l4bDg3WTZXOGw1NEI5YzJRaFpVRlZMTkVtc3dXUUdjdXBicE5uVnArZ0lmUkx3UVl1VjQxQnZZYzRNeVg0ZGI0VWc1UVA3dWhsRU9XVWl1RkVmTUJyWWVQc1V0Ui9uQk53SURGSVJlVGx6MXFoejJOcmNveGl3dkNGQ1VtV3U4NkJRdXE1TDF3UENGRDRZdDdSSldPelVCYnI0ejlWeklsQ2FUUkEyUEtOZHUyN1NmUnlHYnF2RnpSVWNMN29Na2FnbEVmZnJwcnRVU1FEZUEzRmVpczJ6N3R2ZlBpbkplNWhBb0ptZ3JrWlhUbWFEODQ2bllIUloweXlXOUNzdkEyUmU0UHcxMmpwZldkblQyeTBZZmJZPSRWQjM5M00vUytlOD0?initialWidth=916&amp;childId=creditHtmlForm&amp;parentTitle=LEED%20Online&amp;parentUrl=https%3A%2F%2Fleedonline-stg.usgbc.org%2FForm%2Fsimpleform%3F__creditId%3DEBCTSS113L-1000160401%26__creditShortId%3DSS113%26creditHash%3Dabc55552e45163c2e1763d437f096dae%26projectId%3D1000160401</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1330px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditHtmlForm&quot;)/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='creditHtmlForm']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit library'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
