<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Status</name>
   <tag></tag>
   <elementGuidId>58d92b3c-fd88-4282-8277-b7d6e78887e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;4627f5c39bdac97ff01e6dc053965e80&quot;]/div[4]/div/div/h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;4627f5c39bdac97ff01e6dc053965e80&quot;]/div[4]/div/div/h3</value>
   </webElementXpaths>
</WebElementEntity>
